#define BUILDINSTP_SSID = "ElusiveWay(ESP32)"
#define BUILDINSTP_PASSWORD = "12345678"

#ifndef BUILDINSTP_SSID,BUILDINSTP_PASSWORD
#define SSID_ADDRESS "ElusiveWay(ESP32)"
#define BUILDINSTP_PASSWORD = "00000000"
#endif
